version: "3.8"

services:
  app:
    image: app
    build:
      context: ./app
      dockerfile: Dockerfile.development
    container_name: "app_container"
    ports:
      - 8000:8000
    command: python /app/src/manage.py runserver 0.0.0.0:8000
    env_file:
      - "./app/.env.development"
    depends_on:
      - postgres
    volumes:
      - ./app/src:/app/src
      - ./app/src/logs:/logs
  postgres:
    image: postgres:16-alpine
    container_name: "postgres_container"
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=first_django_app_db
    volumes:
      - /usr/first_django_app_db/data/postgresql:/var/lib/postgresql/data