version: "3.8"

services:
  app:
    image: app
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: "django_starter_app"
    expose:
      - 8000:8000
    command: sh -c "python /app/src/manage.py runserver"
    env_file:
      - "./app/.env.app.production"
    depends_on:
      - postgres
    volumes:
      - ./app/src:/app/src
      - ./app/src/logs:/logs

  postgres:
    image: postgres:16-alpine
    container_name: "django_starter_db"
    env_file:
      - "./app/.env.app.production"
    volumes:
      - /usr/first_django_app_db/data/postgresql:/var/lib/postgresql/data